### ISSUE TITLE
add ability to copy text from the chats

### ISSUE THREAD

**Issue by henning-schild** [RikudouSage/harbour-chatgpt#27]
i gave this app a try but did not find a way to copy text out to paste it into other applications, maybe i just did not figure it out, or the feature is missing

**Comment by RikudouSage** [comment]
You can tap the response and it should be copied into clipboard.

**Comment by henning-schild** [comment]
Oh i see, that is a rather hidden feature which i do not think people would expect. I clicked around waiting for a way to select parts of the answer and nothing happened.

I suggest to add some popup ways says "message copied to clipboard" so people get feedback when they tap around.

**Comment by henning-schild** [comment]
Thanks for taking that suggestion!

**Comment by RikudouSage** [comment]
The fix has been implemented, though it will be released at a later date, when translations are ready. If you want it sooner, you can download it from the build artifacts: https://github.com/RikudouSage/harbour-chatgpt/actions/runs/5577553384

**Comment by henning-schild** [comment]
I just received the update and now the "copy to clipboard" feature is not a hidden feature any longer. Thanks!
